public class Utility{
    public static Boolean firstRun = true;
    public static Boolean NfyBillExeRun = true;
    public static Boolean NfyFinanceRun = true;
    public static Boolean MainTriggerRrdRun = true;
    public static Boolean invCreateRun = true;
    public static Boolean doGTO = true;
    public static Boolean doDiscount = true;
    public static Boolean updateLPRun = true;
    public static Boolean updatePOS = true;
    public static Boolean invoiceOnce = true;
    public static String lastUpdatedFromAwsIntegration = 'SF';
}